[libraries]
kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.12.0" }
grammarKitPlugin = { module = "org.jetbrains.intellij.plugins:gradle-grammarkit-plugin", version = "2022.3"}

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version = "1.7.22" }
spotless = { id = "com.diffplug.spotless", version = "6.12.0" }
publish = { id = "com.vanniktech.maven.publish", version = "0.22.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.7.20" }
