name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17

    - uses: gradle/actions/setup-gradle@v4

    - name: Build the project
      run: ./gradlew build
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        path: build/reports/tests/test
